version: "3.3"
services:
  server:
    build: .
    ports:
      - "5050:5050"
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/matcha?schema=public
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - "5432:5432"
volumes:
  postgres:
